# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: base/button.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='base/button.proto',
  package='base',
  syntax='proto3',
  serialized_pb=_b('\n\x11\x62\x61se/button.proto\x12\x04\x62\x61se\"$\n\x0b\x42uttonEvent\x12\x15\n\rbutton_number\x18\x01 \x01(\x05\"@\n\x0bSensorState\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x14\n\x0cnative_value\x18\x02 \x01(\x05\x12\x0f\n\x07pressed\x18\x03 \x01(\x08\"S\n\x0cSensorStates\x12\r\n\x05shelf\x18\x01 \x01(\x05\x12!\n\x06states\x18\x02 \x03(\x0b\x32\x11.base.SensorState\x12\x11\n\tsensor_id\x18\x03 \x01(\x05\x42.Z,git.smass.tech/common/libgo/protocol/toshibab\x06proto3')
)




_BUTTONEVENT = _descriptor.Descriptor(
  name='ButtonEvent',
  full_name='base.ButtonEvent',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='button_number', full_name='base.ButtonEvent.button_number', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=27,
  serialized_end=63,
)


_SENSORSTATE = _descriptor.Descriptor(
  name='SensorState',
  full_name='base.SensorState',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='base.SensorState.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='native_value', full_name='base.SensorState.native_value', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pressed', full_name='base.SensorState.pressed', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=65,
  serialized_end=129,
)


_SENSORSTATES = _descriptor.Descriptor(
  name='SensorStates',
  full_name='base.SensorStates',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='shelf', full_name='base.SensorStates.shelf', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='states', full_name='base.SensorStates.states', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sensor_id', full_name='base.SensorStates.sensor_id', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=131,
  serialized_end=214,
)

_SENSORSTATES.fields_by_name['states'].message_type = _SENSORSTATE
DESCRIPTOR.message_types_by_name['ButtonEvent'] = _BUTTONEVENT
DESCRIPTOR.message_types_by_name['SensorState'] = _SENSORSTATE
DESCRIPTOR.message_types_by_name['SensorStates'] = _SENSORSTATES
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ButtonEvent = _reflection.GeneratedProtocolMessageType('ButtonEvent', (_message.Message,), dict(
  DESCRIPTOR = _BUTTONEVENT,
  __module__ = 'base.button_pb2'
  # @@protoc_insertion_point(class_scope:base.ButtonEvent)
  ))
_sym_db.RegisterMessage(ButtonEvent)

SensorState = _reflection.GeneratedProtocolMessageType('SensorState', (_message.Message,), dict(
  DESCRIPTOR = _SENSORSTATE,
  __module__ = 'base.button_pb2'
  # @@protoc_insertion_point(class_scope:base.SensorState)
  ))
_sym_db.RegisterMessage(SensorState)

SensorStates = _reflection.GeneratedProtocolMessageType('SensorStates', (_message.Message,), dict(
  DESCRIPTOR = _SENSORSTATES,
  __module__ = 'base.button_pb2'
  # @@protoc_insertion_point(class_scope:base.SensorStates)
  ))
_sym_db.RegisterMessage(SensorStates)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('Z,git.smass.tech/common/libgo/protocol/toshiba'))
# @@protoc_insertion_point(module_scope)
